"""Change TextContent model

Revision ID: 2c81b237ef39
Revises: 55d59b55653c
Create Date: 2026-08-30 16:47:32.685745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c81b237ef39'
down_revision: Union[str, Sequence[str], None] = '55d59b55653c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_contents_campaign_id'), table_name='text_contents')
    op.drop_index(op.f('ix_text_contents_post_id'), table_name='text_contents')
    op.drop_constraint(op.f('text_contents_post_id_fkey'), 'text_contents', type_='foreignkey')
    op.drop_constraint(op.f('text_contents_campaign_id_fkey'), 'text_contents', type_='foreignkey')
    op.drop_column('text_contents', 'post_id')
    op.drop_column('text_contents', 'campaign_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_contents', sa.Column('campaign_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('text_contents', sa.Column('post_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('text_contents_campaign_id_fkey'), 'text_contents', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('text_contents_post_id_fkey'), 'text_contents', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_text_contents_post_id'), 'text_contents', ['post_id'], unique=False)
    op.create_index(op.f('ix_text_contents_campaign_id'), 'text_contents', ['campaign_id'], unique=False)
    # ### end Alembic commands ###
